### ISSUE TITLE
[CHECKLIST] Update circuits to use optimized poseidon implementation

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/protocol-solidity#118]
# Overview 

- [ ] Recompile our circuits with the optimized poseidon implementation
- [ ] Remove circuits/anchor and rename circuits/bridge to circuits/anchor
- [ ] Update the build scripts
- [ ] Build our system with Plonk
- [ ] Changing vbridge/bridge language to vanchor/anchor language
