### ISSUE TITLE
[CHECKLIST] New bridge deployment configured with DKG governance

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/protocol-solidity#172]
## Overview

Deploy new bridge(s) that utilizes the DKG, specifically Tangle. This issue is in reference to the Notion page - [Bridge Deployment Checklist](https://www.notion.so/Bridge-Deployment-Checklist-15b9d69d04e24937a4c63fdc630f86cb)

## Goals
- Deploy an EVM - Substrate bridge
    - TNT token should be made available on the bridge
- Deploy an 8-sided bridge but only with (1) EVM chain, and (1) Tangle chain (e.g. 2/8 edges)
    - Ethereum Goerli - see [Bridge Testnet Deployments Options](https://www.notion.so/Bridge-Testnet-Deployments-Options-846bbf7802154d97bad79ea745f458a1) for chain details
    - Tangle Network
    - Ensure the DKG is governor and not mocked
    - Allows us to test adding chains to open edges
- Ensure the Tangle runtime has all required pallets to facilitate E2E tests
- Run E2E tests between bridge - relayer - DKG
- Add and test bridge registry pallet to Tangle runtime
    - Lowest priority on *this* list
    - Allows us to investigate having the relayer read from registry to fetch active configurations
        - Could enable us to deploy a relayer admin dashboard for adding / removing various bridge configurations

# Action Items

- [ ]  Review bridge deployment steps (linked at the bottom)
- [ ]  Ensure Tangle runtime has required pallets (e.g. vanchor)
- [ ]  Go step-by-step and deploy an 8-sided bridge with `Ethereum Goerli` and `Tangle Network`
- [ ]  Document the steps taken to deploy / test bridge
- [ ]  Deploy a relayer with newly deployed bridge configurations
- [ ]  Test a bridge deposit, transfer, and withdraw
- [ ]  Document and report any issues / bugs identified
- [ ]  Review required steps to add a chain to an existing bridge edge
- [ ]  Deploy `Ethereum Sepoli` to the existing bridge instance
- [ ]  Document the steps taken to add chain to the existing bridge instance
- [ ]  Deploy a relayer with newly deployed bridge configuration
- [ ]  Test a bridge deposit, transfer, and withdraw
- [ ]  Add and test bridge registry pallet to Tangle runtime
- [ ]  Perform a runtime upgrade to include pallet

## Relevant Links

- [Current Bridge Deployment Steps](https://www.notion.so/Current-Bridge-Deployment-Steps-1d58deb2c3cb4e609572d83ffa01cf20)

**Comment by dutterbutter** [comment]
@nepoche please provide additional details.
