### ISSUE TITLE
[TASK] Implement EdDSA Verification in Solidity and test with MASP key

### ISSUE THREAD

**Issue by saiakilesh** [webb-tools/protocol-solidity#288]
## TODOs
- [x] Use `MaspKey.ts` to generate keys. Specifically, use the `randomize_sk_ak_alpha` to create `(sk_alpha, ak_alpha)` keypair.
- [x] Sign some dummy message with `(sk_alpha, ak_alpha)`.
- [x] Use https://github.com/HarryR/ethsnarks/blob/master/contracts/EdDSA.sol to try and verify this sig with Solidity.
- [x] Benchmark gas costs.

**Comment by saiakilesh** [comment]
Approximate gas cost is 600K:

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/7463414/231775985-a3d7803c-5044-4591-9e79-0340ee3d4be3.png">


Code is here: https://github.com/webb-tools/protocol-solidity/pull/298
